
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Language = {
  EN: 'EN',
  UA: 'UA',
  RU: 'RU'
} as const

export type Language = (typeof Language)[keyof typeof Language]
