// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: menu-item.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "menu_item.v1";

/** MenuItem represents a menu item with its details. */
export interface MenuItem {
  id: string;
  language: string;
  title: string;
  description?: string | null | undefined;
  price: string;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  position: number;
  createdAt: Date | null;
  updatedAt: Date | null;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** MenuItemList represents a list of menu items. */
export interface MenuItemList {
  menuItems: MenuItem[];
}

/** Request message for creating a menu item. */
export interface CreateMenuItemRequest {
  language: string;
  title: string;
  description?: string | null | undefined;
  price: string;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
  menuCategory: Id | null;
}

/** Request message for updating a menu item. */
export interface UpdateMenuItemRequest {
  id: string;
  language?: string | null | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
  price?: string | null | undefined;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
  menuCategory: Id | null;
}

/** Request message for changing the position of a menu item. */
export interface ChangeMenuItemPositionRequest {
  id: string;
  position: number;
}

/** StatusResponse represents a standard response message indicating success or failure. */
export interface StatusResponse {
  success: boolean;
  message: string;
}

export const MENU_ITEM_V1_PACKAGE_NAME = "menu_item.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

/** MenuItemService defines the gRPC service for managing menu items. */

export interface MenuItemServiceClient {
  /** rpc to get menu items by category ID */

  getMenuItemsByCategoryId(request: Id): Observable<MenuItemList>;

  /** rpc to get a menu item by its ID */

  getMenuItemById(request: Id): Observable<MenuItem>;

  /** rpc to create a new menu item */

  createMenuItem(request: CreateMenuItemRequest): Observable<MenuItem>;

  /** rpc to update an existing menu item */

  updateMenuItem(request: UpdateMenuItemRequest): Observable<MenuItem>;

  /** rpc to change the position of a menu item */

  changeMenuItemPosition(request: ChangeMenuItemPositionRequest): Observable<MenuItem>;

  /** rpc to delete a menu item by its ID */

  deleteMenuItem(request: Id): Observable<StatusResponse>;
}

/** MenuItemService defines the gRPC service for managing menu items. */

export interface MenuItemServiceController {
  /** rpc to get menu items by category ID */

  getMenuItemsByCategoryId(request: Id): Promise<MenuItemList> | Observable<MenuItemList> | MenuItemList;

  /** rpc to get a menu item by its ID */

  getMenuItemById(request: Id): Promise<MenuItem> | Observable<MenuItem> | MenuItem;

  /** rpc to create a new menu item */

  createMenuItem(request: CreateMenuItemRequest): Promise<MenuItem> | Observable<MenuItem> | MenuItem;

  /** rpc to update an existing menu item */

  updateMenuItem(request: UpdateMenuItemRequest): Promise<MenuItem> | Observable<MenuItem> | MenuItem;

  /** rpc to change the position of a menu item */

  changeMenuItemPosition(request: ChangeMenuItemPositionRequest): Promise<MenuItem> | Observable<MenuItem> | MenuItem;

  /** rpc to delete a menu item by its ID */

  deleteMenuItem(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function MenuItemServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getMenuItemsByCategoryId",
      "getMenuItemById",
      "createMenuItem",
      "updateMenuItem",
      "changeMenuItemPosition",
      "deleteMenuItem",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MenuItemService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MenuItemService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MENU_ITEM_SERVICE_NAME = "MenuItemService";
