// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: menu-category.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "menu_category.v1";

/** declaration of Language message */
export interface Language {
  language: string;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** Message representing a list of menu categories */
export interface MenuCategoryList {
  data: MenuCategory[];
}

/** Message representing a list of menu categories with items */
export interface MenuCategoryListWithItems {
  data: MenuCategoryWithItems[];
}

/** Message representing a menu category */
export interface MenuCategory {
  id: string;
  language: string;
  title: string;
  description?: string | null | undefined;
  position: number;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface MenuItem {
  id: string;
  title: string;
  description?: string | null | undefined;
  price: string;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  position: number;
}

/** Message representing a menu category with items */
export interface MenuCategoryWithItems {
  id: string;
  language: string;
  title: string;
  description?: string | null | undefined;
  position: number;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  menuItems: MenuItem[];
}

/** Request message for creating a menu category. */
export interface CreateMenuCategoryRequest {
  language: string;
  title: string;
  description?: string | null | undefined;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
}

/** Request message for updating a menu category. */
export interface UpdateMenuCategoryRequest {
  id: string;
  language?: string | null | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
}

/** Request message for changing the position of a menu category. */
export interface ChangeMenuCategoryPositionRequest {
  id: string;
  position: number;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

export const MENU_CATEGORY_V1_PACKAGE_NAME = "menu_category.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

/** MenuCategoryService defines the gRPC service for managing menu categories. */

export interface MenuCategoryServiceClient {
  /** rpc to get full menu by language */

  getFullMenuByLanguage(request: Language): Observable<MenuCategoryListWithItems>;

  /** rpc to get menu categories by language */

  getMenuCategoriesByLanguage(request: Language): Observable<MenuCategoryList>;

  /** rpc to get a menu category by its ID */

  getMenuCategoryById(request: Id): Observable<MenuCategory>;

  /** rpc to create a new menu category */

  createMenuCategory(request: CreateMenuCategoryRequest): Observable<MenuCategory>;

  /** rpc to update an existing menu category */

  updateMenuCategory(request: UpdateMenuCategoryRequest): Observable<MenuCategory>;

  /** rpc to change the position of a menu category */

  changeMenuCategoryPosition(request: ChangeMenuCategoryPositionRequest): Observable<MenuCategory>;

  /** rpc to delete a menu category by its ID */

  deleteMenuCategory(request: Id): Observable<StatusResponse>;
}

/** MenuCategoryService defines the gRPC service for managing menu categories. */

export interface MenuCategoryServiceController {
  /** rpc to get full menu by language */

  getFullMenuByLanguage(
    request: Language,
  ): Promise<MenuCategoryListWithItems> | Observable<MenuCategoryListWithItems> | MenuCategoryListWithItems;

  /** rpc to get menu categories by language */

  getMenuCategoriesByLanguage(
    request: Language,
  ): Promise<MenuCategoryList> | Observable<MenuCategoryList> | MenuCategoryList;

  /** rpc to get a menu category by its ID */

  getMenuCategoryById(request: Id): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to create a new menu category */

  createMenuCategory(
    request: CreateMenuCategoryRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to update an existing menu category */

  updateMenuCategory(
    request: UpdateMenuCategoryRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to change the position of a menu category */

  changeMenuCategoryPosition(
    request: ChangeMenuCategoryPositionRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to delete a menu category by its ID */

  deleteMenuCategory(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function MenuCategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getFullMenuByLanguage",
      "getMenuCategoriesByLanguage",
      "getMenuCategoryById",
      "createMenuCategory",
      "updateMenuCategory",
      "changeMenuCategoryPosition",
      "deleteMenuCategory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MenuCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MenuCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MENU_CATEGORY_SERVICE_NAME = "MenuCategoryService";
